name: goreleaser

on:
    push:
        tags:
            - '*'

permissions:
    contents: write

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-go@v4
              with:
                  go-version: stable
            - uses: golangci/golangci-lint-action@v3
              with:
                  version: latest
                  args: --timeout=5m
    goreleaser:
        runs-on: ubuntu-latest
        needs: lint
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - run: git fetch --force --tags
            - uses: actions/setup-go@v4
              with:
                  go-version: stable
            - uses: goreleaser/goreleaser-action@v4
              with:
                  distribution: goreleaser
                  version: latest
                  args: release --clean
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
